# Generated by Django 5.2 on 2025-04-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_industry_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachment',
        ),
    ]
