# Generated by Django 5.2 on 2025-05-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_attachment_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
