# Generated by Django 5.2 on 2025-05-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_project_project_image_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project_images/mac.png', null=True, upload_to='project_images/'),
        ),
    ]
