# Generated by Django 5.2 on 2025-05-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
