# Generated by Django 5.2 on 2025-05-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_projectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
