# Generated by Django 5.2 on 2025-05-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='connected_users',
            field=models.ManyToManyField(blank=True, related_name='connections', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project_images/mac.png', null=True, upload_to='project_images/'),
        ),
    ]
