# Generated by Django 5.2 on 2025-05-05 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
