# Generated by Django 5.2 on 2025-05-05 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_patent_date_filed_remove_patent_invention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='connections',
        ),
        migrations.AddField(
            model_name='customuser',
            name='connected_users',
            field=models.ManyToManyField(blank=True, related_name='connections_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='connected_users',
            field=models.ManyToManyField(blank=True, related_name='profile_connections', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='profile_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
