# Generated by Django 5.2 on 2025-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='This is a sample project description for testing purposes.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Sample Project Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_link',
            field=models.URLField(blank=True, default='http://example.com', null=True),
        ),
    ]
