# Generated by Django 5.1.7 on 2026-03-19 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_project_interested_project_promoted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superadmin', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_projects', models.BooleanField(default=False)),
                ('can_manage_posts', models.BooleanField(default=False)),
                ('can_manage_messages', models.BooleanField(default=False)),
                ('can_manage_events', models.BooleanField(default=False)),
                ('can_manage_jobs', models.BooleanField(default=False)),
                ('can_manage_comments', models.BooleanField(default=False)),
                ('can_manage_connections', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_admin_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
