# Generated by Django 5.1.7 on 2026-03-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_event_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
