# Generated by Django 5.1.7 on 2026-03-24 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_event_image_newsitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('post', 'Post Discussion'), ('project', 'Project Discussion')], default='direct', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.post'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.project'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
