# Generated by Django 5.1.7 on 2026-03-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_conversation_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='core.conversation'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='counter_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='counter_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='context_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('post', 'Post Discussion'), ('project', 'Project Discussion'), ('proposal', 'Proposal Discussion')], default='direct', max_length=10),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('countered', 'Countered'), ('on_hold', 'On Hold'), ('reviewing', 'Reviewing')], default='pending', max_length=20),
        ),
    ]
