# Generated by Django 5.1.7 on 2026-03-24 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_proposal_counter_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('idea', '💡 Idea'), ('article', '📝 Article'), ('update', '🚀 Update'), ('announcement', '📢 Announcement'), ('question', '❓ Question')], default='article', max_length=20),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='core.post')),
            ],
        ),
    ]
