# Generated by Django 5.1.7 on 2026-03-26 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_attachment_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='context_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('post', 'Post Discussion'), ('project', 'Project Discussion'), ('proposal', 'Proposal Discussion'), ('collab', 'Collaboration Discussion')], default='direct', max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private groups require admin approval to join'),
        ),
        migrations.CreateModel(
            name='ReadLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_later_saves', to='core.company')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_later_saves', to='core.post')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_later_saves', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_later_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
