# Generated by Django 5.1.7 on 2026-03-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_read_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='postimage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
