# Generated by Django 5.1.7 on 2026-03-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_post_image_name_postimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='feedback_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('bug', 'Bug / Issue'), ('suggestion', 'Suggestion'), ('praise', 'Praise'), ('question', 'Question'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='page',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='section',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
