# Generated by Django 5.1.7 on 2026-03-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_surveyresponse_feedback_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_description',
            field=models.TextField(blank=True, default='', help_text='Short description of the video content (helps search engines)'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_name',
            field=models.CharField(blank=True, default='', help_text='Title shown on/near the video (also used for SEO)', max_length=255),
        ),
    ]
