# Generated by Django 5.1.7 on 2026-03-26 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_add_project_video_seo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDiscussionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='group_discussion_images/')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.groupdiscussion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PagePostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page_post_images/')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='core.pagepost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
