# Generated by Django 5.1.7 on 2026-03-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_add_group_page_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='Comma-separated keywords for search engines (e.g. solar energy, renewable, off-grid)', max_length=500),
        ),
    ]
