# Generated by Django 5.1.7 on 2026-03-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_add_project_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
    ]
