# Generated by Django 5.1.7 on 2026-03-29 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_attachment_description_alter_attachment_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpermissions',
            options={'verbose_name_plural': 'Admin Permissions'},
        ),
        migrations.AddField(
            model_name='collaboration',
            name='innovator_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='innovator_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patentrequest',
            name='innovator_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patentrequest',
            name='innovator_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='innovator_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='innovator_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.comment'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('health', 'Healthcare'), ('edu', 'Education'), ('energy', 'Energy'), ('agriculture', 'Agriculture'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='default_company.png', upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupdiscussioncomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.groupdiscussioncomment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('connected', 'Connected'), ('message_sent', 'Message Sent'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectcollaboration',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_collaborations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcollaboration',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_on_project', to='core.project'),
        ),
        migrations.AlterField(
            model_name='projectcollaboration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('on_hold', 'On Hold'), ('reviewing', 'Reviewing')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.projectcomment'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_proposals', to='core.project'),
        ),
        migrations.AlterField(
            model_name='readlater',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_later_saves', to='core.company'),
        ),
        migrations.AlterField(
            model_name='readlater',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_later_saves', to='core.post'),
        ),
        migrations.AlterField(
            model_name='readlater',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_later_saves', to='core.project'),
        ),
    ]
