# Generated by Django 5.1.7 on 2026-03-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_sync_models_and_agreement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='counter_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='equity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('countered', 'Countered'), ('on_hold', 'On Hold'), ('reviewing', 'Reviewing')], default='pending', max_length=20),
        ),
    ]
