# Generated by Django 5.1.7 on 2026-04-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_services_and_events'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pitchrequest',
            name='unique_pitch_request',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='admin_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='topic',
            field=models.CharField(blank=True, default='General Inquiry', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultingrequest',
            name='description',
            field=models.TextField(help_text='Describe the challenge or support needed'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, help_text='Estimated hours to complete'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='0–100 percent complete'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='availability',
            field=models.CharField(blank=True, default='', help_text='e.g. Weekends, Tuesdays 6–8pm', max_length=200),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='industries',
            field=models.CharField(blank=True, default='', help_text='Comma-separated', max_length=500),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='goals',
            field=models.TextField(blank=True, default='', help_text='What do you want to achieve?'),
        ),
        migrations.AlterUniqueTogether(
            name='pitchrequest',
            unique_together={('project', 'investor')},
        ),
    ]
