# Generated by Django 5.1.7 on 2026-04-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_contact_submission_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user')},
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='emoji',
            field=models.CharField(max_length=32),
        ),
    ]
