# Generated by Django 5.1.7 on 2026-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_message_reaction_one_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
