# Generated by Django 5.1.7 on 2026-04-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_subscription_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('post_share', 'Shared Post'), ('project_share', 'Shared Project')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_shares', to='core.post'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_shares', to='core.project'),
        ),
    ]
