# Generated by Django 5.1.7 on 2026-04-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_message_share_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', help_text='City and/or country (e.g. Nairobi, Kenya)', max_length=150),
        ),
    ]
