# Generated by Django 5.1.7 on 2026-04-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_add_location_to_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Custom industries',
                'ordering': ['name'],
            },
        ),
    ]
