# Generated by Django 5.2.13 on 2026-04-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileview',
            name='session_key',
            field=models.CharField(max_length=255),
        ),
    ]
