# Generated by Django 5.2.13 on 2026-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_profileview_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectview',
            name='session_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
