# Generated by Django 5.2.13 on 2026-04-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_fix_projectview_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance & Banking'), ('health', 'Healthcare'), ('edu', 'Education'), ('energy', 'Energy & Utilities'), ('agriculture', 'Agriculture & Farming'), ('manufacturing', 'Manufacturing'), ('media', 'Media & Entertainment'), ('retail', 'Retail & E-commerce'), ('real_estate', 'Real Estate & Construction'), ('transport', 'Transportation & Logistics'), ('food', 'Food & Beverage'), ('hospitality', 'Tourism & Hospitality'), ('telecom', 'Telecommunications'), ('legal', 'Legal & Compliance'), ('consulting', 'Consulting & Professional Services'), ('marketing', 'Marketing & Advertising'), ('hr', 'Human Resources & Staffing'), ('government', 'Government & Public Sector'), ('nonprofit', 'Non-Profit & NGO'), ('sports', 'Sports & Recreation'), ('fashion', 'Fashion & Apparel'), ('automotive', 'Automotive'), ('aerospace', 'Aerospace & Defense'), ('mining', 'Mining & Metals'), ('chemicals', 'Chemicals & Materials'), ('biotech', 'Biotechnology'), ('cybersecurity', 'Cybersecurity'), ('ai', 'Artificial Intelligence'), ('cleantech', 'Environmental & Clean Tech'), ('insurance', 'Insurance'), ('pharma', 'Pharmaceuticals'), ('design', 'Architecture & Design'), ('research', 'Research & Development'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance & Banking'), ('health', 'Healthcare'), ('edu', 'Education'), ('energy', 'Energy & Utilities'), ('agriculture', 'Agriculture & Farming'), ('manufacturing', 'Manufacturing'), ('media', 'Media & Entertainment'), ('retail', 'Retail & E-commerce'), ('real_estate', 'Real Estate & Construction'), ('transport', 'Transportation & Logistics'), ('food', 'Food & Beverage'), ('hospitality', 'Tourism & Hospitality'), ('telecom', 'Telecommunications'), ('legal', 'Legal & Compliance'), ('consulting', 'Consulting & Professional Services'), ('marketing', 'Marketing & Advertising'), ('hr', 'Human Resources & Staffing'), ('government', 'Government & Public Sector'), ('nonprofit', 'Non-Profit & NGO'), ('sports', 'Sports & Recreation'), ('fashion', 'Fashion & Apparel'), ('automotive', 'Automotive'), ('aerospace', 'Aerospace & Defense'), ('mining', 'Mining & Metals'), ('chemicals', 'Chemicals & Materials'), ('biotech', 'Biotechnology'), ('cybersecurity', 'Cybersecurity'), ('ai', 'Artificial Intelligence'), ('cleantech', 'Environmental & Clean Tech'), ('insurance', 'Insurance'), ('pharma', 'Pharmaceuticals'), ('design', 'Architecture & Design'), ('research', 'Research & Development'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance & Banking'), ('health', 'Healthcare'), ('edu', 'Education'), ('energy', 'Energy & Utilities'), ('agriculture', 'Agriculture & Farming'), ('manufacturing', 'Manufacturing'), ('media', 'Media & Entertainment'), ('retail', 'Retail & E-commerce'), ('real_estate', 'Real Estate & Construction'), ('transport', 'Transportation & Logistics'), ('food', 'Food & Beverage'), ('hospitality', 'Tourism & Hospitality'), ('telecom', 'Telecommunications'), ('legal', 'Legal & Compliance'), ('consulting', 'Consulting & Professional Services'), ('marketing', 'Marketing & Advertising'), ('hr', 'Human Resources & Staffing'), ('government', 'Government & Public Sector'), ('nonprofit', 'Non-Profit & NGO'), ('sports', 'Sports & Recreation'), ('fashion', 'Fashion & Apparel'), ('automotive', 'Automotive'), ('aerospace', 'Aerospace & Defense'), ('mining', 'Mining & Metals'), ('chemicals', 'Chemicals & Materials'), ('biotech', 'Biotechnology'), ('cybersecurity', 'Cybersecurity'), ('ai', 'Artificial Intelligence'), ('cleantech', 'Environmental & Clean Tech'), ('insurance', 'Insurance'), ('pharma', 'Pharmaceuticals'), ('design', 'Architecture & Design'), ('research', 'Research & Development'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance & Banking'), ('health', 'Healthcare'), ('edu', 'Education'), ('energy', 'Energy & Utilities'), ('agriculture', 'Agriculture & Farming'), ('manufacturing', 'Manufacturing'), ('media', 'Media & Entertainment'), ('retail', 'Retail & E-commerce'), ('real_estate', 'Real Estate & Construction'), ('transport', 'Transportation & Logistics'), ('food', 'Food & Beverage'), ('hospitality', 'Tourism & Hospitality'), ('telecom', 'Telecommunications'), ('legal', 'Legal & Compliance'), ('consulting', 'Consulting & Professional Services'), ('marketing', 'Marketing & Advertising'), ('hr', 'Human Resources & Staffing'), ('government', 'Government & Public Sector'), ('nonprofit', 'Non-Profit & NGO'), ('sports', 'Sports & Recreation'), ('fashion', 'Fashion & Apparel'), ('automotive', 'Automotive'), ('aerospace', 'Aerospace & Defense'), ('mining', 'Mining & Metals'), ('chemicals', 'Chemicals & Materials'), ('biotech', 'Biotechnology'), ('cybersecurity', 'Cybersecurity'), ('ai', 'Artificial Intelligence'), ('cleantech', 'Environmental & Clean Tech'), ('insurance', 'Insurance'), ('pharma', 'Pharmaceuticals'), ('design', 'Architecture & Design'), ('research', 'Research & Development'), ('other', 'Other')], default='tech', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance & Banking'), ('health', 'Healthcare'), ('edu', 'Education'), ('energy', 'Energy & Utilities'), ('agriculture', 'Agriculture & Farming'), ('manufacturing', 'Manufacturing'), ('media', 'Media & Entertainment'), ('retail', 'Retail & E-commerce'), ('real_estate', 'Real Estate & Construction'), ('transport', 'Transportation & Logistics'), ('food', 'Food & Beverage'), ('hospitality', 'Tourism & Hospitality'), ('telecom', 'Telecommunications'), ('legal', 'Legal & Compliance'), ('consulting', 'Consulting & Professional Services'), ('marketing', 'Marketing & Advertising'), ('hr', 'Human Resources & Staffing'), ('government', 'Government & Public Sector'), ('nonprofit', 'Non-Profit & NGO'), ('sports', 'Sports & Recreation'), ('fashion', 'Fashion & Apparel'), ('automotive', 'Automotive'), ('aerospace', 'Aerospace & Defense'), ('mining', 'Mining & Metals'), ('chemicals', 'Chemicals & Materials'), ('biotech', 'Biotechnology'), ('cybersecurity', 'Cybersecurity'), ('ai', 'Artificial Intelligence'), ('cleantech', 'Environmental & Clean Tech'), ('insurance', 'Insurance'), ('pharma', 'Pharmaceuticals'), ('design', 'Architecture & Design'), ('research', 'Research & Development'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
