# Generated by Django 5.2.13 on 2026-04-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_expand_industry_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance & Banking'), ('health', 'Healthcare'), ('edu', 'Education'), ('energy', 'Energy & Utilities'), ('agriculture', 'Agriculture & Farming'), ('manufacturing', 'Manufacturing'), ('media', 'Media & Entertainment'), ('retail', 'Retail & E-commerce'), ('real_estate', 'Real Estate & Construction'), ('transport', 'Transportation & Logistics'), ('food', 'Food & Beverage'), ('hospitality', 'Tourism & Hospitality'), ('telecom', 'Telecommunications'), ('legal', 'Legal & Compliance'), ('consulting', 'Consulting & Professional Services'), ('marketing', 'Marketing & Advertising'), ('hr', 'Human Resources & Staffing'), ('government', 'Government & Public Sector'), ('nonprofit', 'Non-Profit & NGO'), ('sports', 'Sports & Recreation'), ('fashion', 'Fashion & Apparel'), ('automotive', 'Automotive'), ('aerospace', 'Aerospace & Defense'), ('mining', 'Mining & Metals'), ('chemicals', 'Chemicals & Materials'), ('biotech', 'Biotechnology'), ('cybersecurity', 'Cybersecurity'), ('ai', 'Artificial Intelligence'), ('cleantech', 'Environmental & Clean Tech'), ('insurance', 'Insurance'), ('pharma', 'Pharmaceuticals'), ('design', 'Architecture & Design'), ('research', 'Research & Development'), ('other', 'Other')], default='tech', max_length=100),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read'], name='msg_recipient_read_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='msg_conv_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notif_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['user', 'timestamp'], name='pv_user_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['path', 'timestamp'], name='pv_path_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'is_hidden'], name='post_user_hidden_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['industry', 'is_hidden'], name='post_industry_hidden_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='post_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'is_hidden'], name='proj_owner_hidden_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['industry', 'is_hidden'], name='proj_industry_hidden_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_hidden'], name='proj_status_hidden_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['pipeline_stage', 'is_hidden'], name='proj_stage_hidden_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='proj_created_idx'),
        ),
    ]
