# Generated by Django 5.2.13 on 2026-04-16 15:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_add_indexes_and_fix_post_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(storage=core.models.ChatAttachmentStorage(), upload_to='chat_attachments/%Y/%m/'),
        ),
    ]
