# Generated by Django 5.2.13 on 2026-04-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_message_is_deleted_is_edited_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
