# Generated by Django 5.2.13 on 2026-04-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_poll_models_and_post_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
        ),
    ]
