# Generated by Django 5.2.13 on 2026-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_add_gender_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_style',
            field=models.CharField(blank=True, default='', help_text='CSS background value for profile banner', max_length=300),
        ),
    ]
