# Generated by Django 5.2.13 on 2026-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_cover_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='website_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
