# Generated by Django 5.2.13 on 2026-04-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_post_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pricing_enabled',
            field=models.BooleanField(default=False, help_text='Show Pricing page and tabs to users'),
        ),
    ]
